### ISSUE TITLE
Page Error

### ISSUE THREAD

**Issue by mingasdf** [IamTheDefender/BedWars1058-Cosmetics-Free#19]
In version 1.4.4 (Or older)
Players cannot scroll to the third or higher page of the Cosmetic gui (page 4, page 5, or higher page), and hologram error still exists.

**Comment by IamTheDefender** [comment]
Are you in the discord server?

**Comment by mingasdf** [comment]
no

**Comment by IamTheDefender** [comment]
I understand that I took too long to reply but I am sorry I had some personal issues. Anyway try this and let me know, https://cdn.discordapp.com/attachments/1000414879674548285/1149710532543250542/BW1058-Cosmetics-1.4.5.jar

**Comment by mingasdf** [comment]
ok, this version fixed this error, thanks.

**Comment by IamTheDefender** [comment]
I am glad to hear that!
