### ISSUE TITLE
Server is crashing & Issue with Projectile Trail (v1.3) 

### ISSUE THREAD

**Issue by shoutzz011** [IamTheDefender/BedWars1058-Cosmetics-Free#4]
After updating the plugin to version 1.3, the server crashes after picking up minerals in the diamond or emerald generator, which makes gameplay difficult and sometimes causes the server to shut down

This same issue was reported on BedWars1058's Github, you can look it up [by clicking here](https://github.com/andrei1058/BedWars1058/issues/679), some other details are there too

**Comment by IamTheDefender** [comment]
Hey shoutzz011, I have tried to fix the issue for you, kindly check out the jar I have attached. Errors are expected with this jar, just let me know. Just unzip the the zip file and you will find the jar.
[cosmetics.zip](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10775673/cosmetics.zip)

**Comment by shoutzz011** [comment]
Hello, sorry for the delay. The problem has been fixed with the one you sent

But on the other hand, your plugin may be causing another problem, it is possible that your plugin is interfering with the "spawn-limit:" of all bw1058 generators (iron/gold/upgrade(emerald)diamond and emerald) that was previously limiting to 4 or 8 depending on the level (which was not what I configured), but now, the island generators simply accumulate ore packs, and in the emerald and diamond generators the same thing basically

**Comment by shoutzz011** [comment]
This console error is also being sent as spam

```[23:29:04 WARN]: [BW1058-Cosmetics] Task #3454 for BW1058-Cosmetics v1.3 generated an exception
java.lang.NullPointerException: particle couldn't find!
        at me.defender.cosmetics.support.hcore.utils.Validate.notNull(Validate.java:37) ~[?:?]
        at me.defender.cosmetics.support.hcore.particle.wrapper.ParticleWrapper_v1_8_R3.play(ParticleWrapper_v1_8_R3.java:39) ~[?:?]
        at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:39) ~[?:?]
        at me.defender.cosmetics.support.hcore.particle.ParticleHandler.lambda$play$1(ParticleHandler.java:61) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:61) ~[?:?]
        at me.defender.cosmetics.support.hcore.HCore.playParticle(HCore.java:615) ~[?:?]
        at me.defender.cosmetics.api.categories.projectiletrails.util.ProjectileEffectsUtil.sendEffect(ProjectileEffectsUtil.java:45) ~[?:?]
        at me.defender.cosmetics.api.categories.projectiletrails.ProjectileHandler$1.run(ProjectileHandler.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by IamTheDefender** [comment]
> This console error is also being sent as spam
> 
> ```
> java.lang.NullPointerException: particle couldn't find!
>         at me.defender.cosmetics.support.hcore.utils.Validate.notNull(Validate.java:37) ~[?:?]
>         at me.defender.cosmetics.support.hcore.particle.wrapper.ParticleWrapper_v1_8_R3.play(ParticleWrapper_v1_8_R3.java:39) ~[?:?]
>         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:39) ~[?:?]
>         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.lambda$play$1(ParticleHandler.java:61) ~[?:?]
>         at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
>         at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
>         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:61) ~[?:?]
>         at me.defender.cosmetics.support.hcore.HCore.playParticle(HCore.java:615) ~[?:?]
>         at me.defender.cosmetics.api.categories.projectiletrails.util.ProjectileEffectsUtil.sendEffect(ProjectileEffectsUtil.java:45) ~[?:?]
>         at me.defender.cosmetics.api.categories.projectiletrails.ProjectileHandler$1.run(ProjectileHandler.java:33) ~[?:?]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
>         at java.lang.Thread.run(Thread.java:834) [?:?]```
> ```

Which Projectile Trail have you selected when this error occurred?

**Comment by shoutzz011** [comment]
> > This console error is also being sent as spam
> > ```
> > java.lang.NullPointerException: particle couldn't find!
> >         at me.defender.cosmetics.support.hcore.utils.Validate.notNull(Validate.java:37) ~[?:?]
> >         at me.defender.cosmetics.support.hcore.particle.wrapper.ParticleWrapper_v1_8_R3.play(ParticleWrapper_v1_8_R3.java:39) ~[?:?]
> >         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:39) ~[?:?]
> >         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.lambda$play$1(ParticleHandler.java:61) ~[?:?]
> >         at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
> >         at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
> >         at me.defender.cosmetics.support.hcore.particle.ParticleHandler.play(ParticleHandler.java:61) ~[?:?]
> >         at me.defender.cosmetics.support.hcore.HCore.playParticle(HCore.java:615) ~[?:?]
> >         at me.defender.cosmetics.api.categories.projectiletrails.util.ProjectileEffectsUtil.sendEffect(ProjectileEffectsUtil.java:45) ~[?:?]
> >         at me.defender.cosmetics.api.categories.projectiletrails.ProjectileHandler$1.run(ProjectileHandler.java:33) ~[?:?]
> >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
> >         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
> >         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
> >         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
> >         at java.lang.Thread.run(Thread.java:834) [?:?]```
> > ```
> 
> Which Projectile Trail have you selected when this error occurred and please send the Particle for the selected Projectile Trail from the YAML file?

sorry for the delay, the "Projectile Trail" selected was "Ender"

**Comment by IamTheDefender** [comment]
And the particle field is set to "END_ROD" right? If yes can try using some other Projectile Trail and check if that error occurs?

Sorry for the late response got a little busy today.

**Comment by shoutzz011** [comment]
> And the particle field is set to "END_ROD" right? If yes can try using some other Projectile Trail and check if that error occurs?
> 
> Sorry for the late response got a little busy today.

Sorry again for the delay, but all sprays are causing this error. i tested them all one by one and the error still happens.

**Comment by IamTheDefender** [comment]
> > And the particle field is set to "END_ROD" right? If yes can try using some other Projectile Trail and check if that error occurs?
> > Sorry for the late response got a little busy today.
> 
> Sorry again for the delay, but all sprays are causing this error. i tested them all one by one and the error still happens.

Sorry for late responses, I am quite busy these days. Anyways, you mean Projectile Trails right? If yes I will look into fixing it as soon as I get some time.

**Comment by shoutzz011** [comment]
Yes exactly, I ended up getting confused
Ah, by the way, the error occurs when using a fireball, using the bow, some tools (I don't remember which ones), but never in a "random" way, it's always in these "events"

**Comment by IamTheDefender** [comment]
Just an update, I still can't figure out this yet

**Comment by IamTheDefender** [comment]
https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/releases/tag/1.3-HOTFIX
