### ISSUE TITLE
This plug-in was loaded, but there was no response when it entered the server.

### ISSUE THREAD

**Issue by SuperLifeown** [IamTheDefender/BedWars1058-Cosmetics-Free#48]
This plug-in was loaded, but there was no response when it entered the server. I used java18, and this is all my plug-ins.
![4a5312ece1c88865205d53839fcd824b](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/163156194/92d2bfe0-7af5-47bd-8557-816ed6924bfb)
![810deb547e6cd8f758ccae1b6481a5b0](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/163156194/c37e5091-70e3-4eff-8f93-d07ee1cba172)

**Comment by IamTheDefender** [comment]
Try using /bwc instead of /BWC
