### ISSUE TITLE
windows defender trojan quarantine alert

### ISSUE THREAD

**Issue by joohnaquino** [IamTheDefender/BedWars1058-Cosmetics-Free#49]
I updated the plugin to version 1.4.7 and a trojan was detected (specifically "androidOS/multiverze") which was instantly blocked by Windows Defender when I started the server and caused it to not complete its start.

Currently my browser (chrome) does not allow downloading the plugin, and when security is disabled, Windows Defender puts the plugin in quarantine, preventing me from running Spigot Antimalware for verification

![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/2ad08672-7024-4b8d-b5c1-3feac282b508)

![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/91e1672e-dd0d-4abb-abe7-3b8005a1d8ac)

**Comment by IamTheDefender** [comment]
Hello,

That is a false positive by Windows Defender,
https://www.spigotmc.org/threads/windows-defender-false-positives.639507/

Do report it as false positive, and you can check the source code as well

**Comment by joohnaquino** [comment]
either way, it will continue to have issues [(like this)](https://github.com/IamTheDefender/Bedwars-Cosmetics/issues/8)
the vault is not detected, and when it is, you still have the same problem of buying any item in the store using gold

**Comment by IamTheDefender** [comment]
Can you provide the exact issue? Does your economy plugin not get detected
or does the plugin not enable?

**Comment by joohnaquino** [comment]
repeating;
- the vault **is not detected** by bw1058 cosmetic, and **when it is**, the error when purchasing any item in the store using gold continues

**Comment by IamTheDefender** [comment]
Didn't ask for you to repeat the same stuff you already said. What is the
error thrown by the plugin when vault is detected, when you try to purchase?

**Comment by joohnaquino** [comment]
![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/331223c9-c869-4218-afec-94cd1505bd0d)

**Comment by joohnaquino** [comment]
![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/0b13ad44-a96f-4c29-af5b-b224b46e47c6)
![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/702695a1-7f94-4a65-aedb-ab8d201c3c6b)

1.4.7 dev build downloaded in your discord
![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/847162f3-9743-4dfa-b660-9d0afe4907d5)

**Comment by IamTheDefender** [comment]
You **need** a **economy** plugin that **supports** vault.

**Comment by joohnaquino** [comment]
config.yml and mainmenu.yml is empty

**Comment by IamTheDefender** [comment]
What does it say when cosmetics is being loaded?

**Comment by joohnaquino** [comment]
bw1058 is in bungee mode, making the plugin when started for the first time use normal mode, in this it tries to connect to the sqlite database, which is not possible because sqlite is not compatible with bw1058-cosmetic in bungee mode
![image](https://github.com/IamTheDefender/Bedwars-Cosmetics/assets/120399502/dda84a66-0859-4e60-bd92-3916e9bfcb93)


I connected bw1058-cosmetic to the database and the server tries to use start.sh when starting completely (I'm looking into this)

**Comment by joohnaquino** [comment]
running "start.sh" apparently only happens when this is done for the first time (same process repeated 3 times on 4 servers)

**Comment by IamTheDefender** [comment]
Yeah, that is a known issue (the config not generating). Also, you'll need to copy the config.yml from the GitHub repo for now. And, one the first load for the cosmetics plugin, it will try to restart the server as to a workaround from a old bug, that is normal.

**Comment by joohnaquino** [comment]
I don't know this has already been reported, but it's appearing to me, I'm not sure when yet. I will analyze
https://mclo.gs/Z93IEkL


I just saw it, it appears when changing the menu/category in the store or in the bw1058 upgrade store

**Comment by IamTheDefender** [comment]
Looks like it didn't generate the messages for the menu. From which version of the plugin did you update? and what is your bedwars1058 version?

**Comment by joohnaquino** [comment]
If that's right, it's my custom lang that I haven't finished yet, in the last bw1058 updates the lang was changed causing problems for my lang

**Comment by IamTheDefender** [comment]
Oh okay, do complete your lang and let me know if the issue persists with the default English lang for bw1058
