### ISSUE TITLE
Connection time out error takes much time when launching the server

### ISSUE THREAD

**Issue by WitheredWinter** [IamTheDefender/BedWars1058-Cosmetics-Free#50]
When the server is starting, the Cosmetics plugin takes a lot of time,making the server takes near 140s to start ([17:19:34 INFO]: Done (139.537s)! For help, type "help"). See the log for more information.

Log here: **https://pastebin.com/9m0bLb87** Starting from line 166

OS: Ubuntu
Java version: 21.0.2
Server: Paper 1.20.4
Plugin version: BedWars-Cosmetics-v1.4.7

**Comment by IamTheDefender** [comment]
Does your server have stable internet connections? and can your server download stuff from dropbox?

**Comment by WitheredWinter** [comment]
NO, the server can't reach Dropbox. Can you make some adjustments so that the server starting process can go on as your plugin try to reach Dropbox?

**Comment by WitheredWinter** [comment]
Or add a alternative source? Anyway, I will appreciate.

**Comment by IamTheDefender** [comment]
You can manually download the schematic file from dropbox and upload it to the island topper folder and rename it to cube.schematic, https://dl.dropboxusercontent.com/s/x9rmk36qa1uwrr3/idkcube.schematic

**Comment by WitheredWinter** [comment]
thank you soooo much!

**Comment by IamTheDefender** [comment]
You are welcome 🙂
