### ISSUE TITLE
Sussy Action :l

### ISSUE THREAD

**Issue by BussyBakks** [IamTheDefender/BedWars1058-Cosmetics-Free#51]
![image](https://github.com/user-attachments/assets/48a3653e-22d1-49c4-9079-7b427abfbd95)
as u can see in the pics thats ur plugins is flagged in Windows Defender is Multiverze Trojan, pls fix
@IamTheDefender

**Comment by IamTheDefender** [comment]
Hello, it's a false positive from Windows Defender, look at https://www.spigotmc.org/threads/windows-defender-false-positives.639507/ and https://www.virustotal.com/gui/file/4946fb87610b7c8562e1991317db29aa5bf6a0b03a195aac1b65b82976b9e17b
