### ISSUE TITLE
NPC abnormal

### ISSUE THREAD

**Issue by A1exey1337** [IamTheDefender/BedWars1058-Cosmetics-Free#6]
why?
![QQ图片20230221201842](https://user-images.githubusercontent.com/70209209/220343415-d94d7cab-ce8d-434e-bc23-e5d7ca869b80.png)
![QQ图片20230221201846](https://user-images.githubusercontent.com/70209209/220343566-3437ea4e-7877-43fe-b9db-4eb470083c7e.png)

**Comment by YingHua233** [comment]
> why? ![QQ图片20230221201842](https://user-images.githubusercontent.com/70209209/220343415-d94d7cab-ce8d-434e-bc23-e5d7ca869b80.png) ![QQ图片20230221201846](https://user-images.githubusercontent.com/70209209/220343566-3437ea4e-7877-43fe-b9db-4eb470083c7e.png)

use bedwars1058 v22.3.4 and 
BedWars1058-Cosmetics v1.3
Java16

**Comment by IamTheDefender** [comment]
Can you send console logs?

**Comment by YingHua233** [comment]
> Can you send console logs?

ok

**Comment by YingHua233** [comment]
> Can you send console logs?

[latest (5).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10793801/latest.5.log)

**Comment by IamTheDefender** [comment]
Can you try using, https://ci.citizensnpcs.co/job/citizens2/2934/

**Comment by YingHua233** [comment]
> Can you try using, https://ci.citizensnpcs.co/job/citizens2/2934/

ok i try

**Comment by YingHua233** [comment]
No difference

**Comment by YingHua233** [comment]
> Can you try using, https://ci.citizensnpcs.co/job/citizens2/2934/

![QQ图片20230221230340](https://user-images.githubusercontent.com/70209209/220381660-b3a7cba4-b30f-4fb5-952d-15959a06df92.png)
only NPCS are affected

**Comment by IamTheDefender** [comment]
> > Can you try using, https://ci.citizensnpcs.co/job/citizens2/2934/
> 
> ![QQ图片20230221230340](https://user-images.githubusercontent.com/70209209/220381660-b3a7cba4-b30f-4fb5-952d-15959a06df92.png) only NPCS are affected

That fixes the issue right? I don't see any issue in that image

**Comment by YingHua233** [comment]
> 

I said MOBS are not affected but NPCS 'skins are

**Comment by IamTheDefender** [comment]
> > 
> 
> I said MOBS are not affected but NPCS 'skins are Maybe I didn't make myself clear I'm sorry

Can you try using the most recent version of citizens from jekins ?

**Comment by YingHua233** [comment]
[latest (6).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10814819/latest.6.log)
![QQ图片20230223225136](https://user-images.githubusercontent.com/70209209/220941845-b915be3f-f2ff-4a17-868a-4865be61c168.png)
use Citizens-2.0.30-b2944.jar

**Comment by IamTheDefender** [comment]
> [latest (6).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10814819/latest.6.log) ![QQ图片20230223225136](https://user-images.githubusercontent.com/70209209/220941845-b915be3f-f2ff-4a17-868a-4865be61c168.png) use Citizens-2.0.30-b2944.jar

I am not sure about this issue but can you try without the LibsDisguises plugin?

**Comment by YingHua233** [comment]
> > [latest (6).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10814819/latest.6.log) ![QQ图片20230223225136](https://user-images.githubusercontent.com/70209209/220941845-b915be3f-f2ff-4a17-868a-4865be61c168.png) use Citizens-2.0.30-b2944.jar
> 
> I am not sure about this issue but can you try without the LibsDisguises plugin?

no thing change

**Comment by IamTheDefender** [comment]
> > > [latest (6).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10814819/latest.6.log) ![QQ图片20230223225136](https://user-images.githubusercontent.com/70209209/220941845-b915be3f-f2ff-4a17-868a-4865be61c168.png) use Citizens-2.0.30-b2944.jar
> > 
> > 
> > I am not sure about this issue but can you try without the LibsDisguises plugin?
> 
> no thing change

enable debug in the config of cosmetics and send the logs

**Comment by YingHua233** [comment]
> > > > [latest (6).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10814819/latest.6.log) ![QQ图片20230223225136](https://user-images.githubusercontent.com/70209209/220941845-b915be3f-f2ff-4a17-868a-4865be61c168.png) use Citizens-2.0.30-b2944.jar
> > > 
> > > 
> > > I am not sure about this issue but can you try without the LibsDisguises plugin?
> > 
> > 
> > no thing change
> 
> enable debug in the config of cosmetics and send the logs
[latest (7).log](https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/files/10872873/latest.7.log)

**Comment by IamTheDefender** [comment]
I am not sure what is causing the issue for you but try using https://github.com/IamTheDefender/BedWars1058-Cosmetics-Free/releases/tag/1.3-HOTFIX if still doesn't work try using different client
