### ISSUE TITLE
Potential resource leaks due to incorrect Hikari usage

### ISSUE THREAD

**Issue by neziw** [IamTheDefender/BedWars1058-Cosmetics-Free#7]
Dear plugin author, I would like to bring to your attention the potential resource leakage issue in the current implementation of the database connection handling in your plugin. The code calls the `getConnection()` method every time a database operation is performed, which creates a new connection object, leading to unnecessary and excessive use of database connections, and hence, resource leakage.

For example, if 80 players join the server at the same time or with a short time interval, up to 80 connections will be created, which will have dangerous consequences. Other plugins may also have problems because the database server will reject further connections due to their excessive (big) amount.

To address this issue, I recommend implementing the Singleton pattern to obtain a single instance of the Connection object to be shared by all operations. This approach ensures efficient and optimal use of database resources and avoids the risk of resource leakage.

I hope you find this feedback helpful and look forward to your response on this matter. If you need help with implementing fix, tell me and I will help you with this. Thank you for your attention to this issue.

**Comment by IamTheDefender** [comment]
I will work on implementing this, as soon as I have enough free time. Thank you for giving me the information, it helps alot!

**Comment by IamTheDefender** [comment]
Implemented.
