### ISSUE TITLE
ShopBuyEvent when buying wood

### ISSUE THREAD

**Issue by shoutzz** [IamTheDefender/BedWars1058-Cosmetics-Free#8]
When buying wood from the store, the below error is shown each and every time I buy wood

https://pastebin.com/CfbvELqt

**Comment by IamTheDefender** [comment]
Can you tell me what is there at `blocks-category.category-content.wood.content-tiers.tier1.tier-settings.currency` in the shop config?

**Comment by shoutzz011** [comment]
![image](https://user-images.githubusercontent.com/120399502/228673073-1771939b-4d97-401c-99c2-c0b37a9f755e.png)

**Comment by IamTheDefender** [comment]
Does this still happen to you (update 1.4.1)?

**Comment by IamTheDefender** [comment]
Because I don't quite see a issue here

**Comment by shoutzz011** [comment]
> Does this still happen to you (update 1.4.1)?

the plugin is already in version 1.4.1
but it shows "1.4"

**Comment by shoutzz011** [comment]
> So the, error points to bedwars1058 getCurrency method, what is the version of bedwars1058?

it's 23.2.1 but the error happens even before that (23.2 and 23.3)

**Comment by IamTheDefender** [comment]
What if you use 22.7?

**Comment by IamTheDefender** [comment]
No reply by the issue owner.
